### ISSUE TITLE
Make it an upstream contribution?

### ISSUE THREAD

**Issue by antoineco** [sho-87/kanagawa-paper.nvim#1]
I dig the colors, it's a nice twist on kanagawa!

Have you considered upstreaming this flavor to the kanagawa repository? It would be a great addition, and would allow switching between kanagawa flavors more easily than with two completely separate projects.

**Comment by sho-87** [comment]
I did consider it, but there are few reasons why I dont think it'll happen. primarily, my desire for a more toned down and muted mix of colors means that in some places it doesnt have high enough contrast ratio to be fully accessibility compliant, which is one of the highlights of the original theme.

**Comment by antoineco** [comment]
Thanks for explaining your reasoning. And again: great work!
