### ISSUE TITLE
Indent line too dark in mini.indentscope 

### ISSUE THREAD

**Issue by plague-doctor** [sho-87/kanagawa-paper.nvim#13]
The indent line is way too dark after last update:
![image](https://github.com/user-attachments/assets/2efe718a-441d-4eaf-9f4f-917908117fbc)

Could you please indicate how to make this line lighter? It became invisible after last update :-(

**Comment by sho-87** [comment]
to change the indent color (or any other hl group), you can add something like this to your opts for the plugin:

```
  {
    "sho-87/kanagawa-paper.nvim",
    lazy = false,
    opts = {
      colors = {
        theme = {
          ui = {
            indent = "#ff0000",
          },
        },
      },
    },
  },
```

see here for more info: https://github.com/sho-87/kanagawa-paper.nvim/issues/3#issuecomment-2183665367
