### ISSUE TITLE
Cannot get transparent floating window to work

### ISSUE THREAD

**Issue by MarcBaeuerle** [sho-87/kanagawa-paper.nvim#16]
I have tried using the sample given in the `README.md` with `lazy` giving me this:
```
  {
    "sho-87/kanagawa-paper.nvim",
    lazy = false,
    priority = 1000,
    opts = {},
    init = function()
      require('kanagawa-paper').setup({
        transparent = true,
        colors = { theme = {}, palette = {} }, -- override default palette and theme colors
        overrides = function()
          return {
            NormalFloat = { bg = "none" },
            FloatBorder = { bg = "none" },
            FloatTitle = { bg = "none" },
          }
        end,
      })

      -- setup must be called before loading
      vim.cmd("colorscheme kanagawa-paper")
      vim.api.nvim_set_hl(0, 'Normal', { bg = 'none' })
      vim.api.nvim_set_hl(0, 'NormalFloat', { bg = 'none' })
    end,
  },

```

with normal kanagawa i just needed
```
vim.api.nvim_set_hl(0, 'Normal', { bg = 'none' })
vim.api.nvim_set_hl(0, 'NormalFloat', { bg = 'none' })
```
inside the init function to set the floating windows transparent so Im not sure what Im doing wrong here.
Thank you for the help!

**Comment by sho-87** [comment]
a couple of things come to mind:

1. you should put those options inside opts to avoid nesting the config. eg:
```
{
    "sho-87/kanagawa-paper.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      transparent = false,
      overrides = function()
        return {
          NormalFloat = { bg = "None" },
        }
      end,
    },
  }
```

2. make sure you have winblend set to a non-zero value: `vim.opt.winblend = 30`. example:
```
  {
    "sho-87/kanagawa-paper.nvim",
    lazy = false,
    priority = 1000,
    init = function()
      vim.opt.winblend = 30
    end,
    opts = {
      transparent = false,
      overrides = function()
        return {
          NormalFloat = { bg = "None" },
        }
      end,
    },
  },
```

fyi your line `vim.api.nvim_set_hl(0, 'NormalFloat', { bg = 'none' })` is effectively doing the same thing as the override function; they're both just setting the bg color of the NormalFloat highlight group to be empty. so you don't need both

the basic config above gives me something that looks like this:
![image](https://github.com/user-attachments/assets/322dffbf-1c4d-49ad-ad29-a0b68c535385)

**Comment by MarcBaeuerle** [comment]
Interesting, it seems to work fine on Mason, but telescope still has the solid background. Ill try to figure something else out

**Comment by sho-87** [comment]
maybe double check your telescopes winblend setting: https://github.com/nvim-telescope/telescope.nvim/blob/master/doc/telescope.txt#L214

https://www.reddit.com/r/neovim/comments/16zwn8i/transparent_floating_windows/

**Comment by MarcBaeuerle** [comment]
Found it,

    opts = {
      transparent = true,
      overrides = function()
        return {
          TelescopeResultsNormal = { bg = "None" },
        }
      end,
    },

 Telescope options can be found here: https://github.com/sho-87/kanagawa-paper.nvim/blob/master/lua/kanagawa-paper/highlights/plugins.lua
