### ISSUE TITLE
FZF theme?

### ISSUE THREAD

**Issue by vizvim** [sho-87/kanagawa-paper.nvim#17]
I'm a big fan of this theme and I was wondering if it would be possible to get a version of this theme for [FZF](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#color-themes)?

**Comment by sho-87** [comment]
hmm I dont use fzf in the terminal much - does it not just pick up the colorscheme that your terminal emulator is using?

if not, is there some custom conf file that it uses to set colors?
