### ISSUE TITLE
Dark fonts on dark background = illegible text

### ISSUE THREAD

**Issue by plague-doctor** [sho-87/kanagawa-paper.nvim#2]
I love the colours of this pallet. Thank you very much for the contribution.
Anyway, some of the colours renders text totally illegible... 

![image](https://github.com/sho-87/kanagawa-paper.nvim/assets/10541916/075badf4-e1ae-4862-a149-8fbb8b4cc562)

or

![image](https://github.com/sho-87/kanagawa-paper.nvim/assets/10541916/1aac554b-245a-45d8-a5ca-a3e34aafef89)

Could you fix that or point me to the right direction what to modify?

**Comment by sho-87** [comment]
good catch. this seems specific to zsh filetypes where things like variables, functions, and operators were linked to none. should be fixed in the latest commit. let me know if i missed anything else
