### ISSUE TITLE
[FEAT] : Add support to mini.completion 

### ISSUE THREAD

**Issue by Yushi5058** [sho-87/kanagawa-paper.nvim#4]
Hello, 
I would like to suggest to add support for the mini.completion plugin so it has consistent colors the same as the colorscheme. 
**Current Output**
![2024-06-26_21-26-32](https://github.com/sho-87/kanagawa-paper.nvim/assets/108335997/32baf1d0-581b-4361-ad2e-37dfaaea52bd)
Thanks for the awesome work,
Yushi

**Comment by SimonHoSprung** [comment]
@Yushi5058 do you mean consistent colors as in the keywords like `function` being the same color as in the buffer?

also, what font are you using? looks nice

**Comment by sho-87** [comment]
@Yushi5058 do you mean consistent colors as in the keywords like function being the same color as in the buffer?

also, what font are you using? looks nice

**Comment by sho-87** [comment]
so for example, this is how it works on my setup (and most setups ive seen):

- the documentation on the right is syntax highlighted
- the type is also correctly highlighted (same as buffer)
- but the name itself is not and is all just the fujiWhite color like regular text

![image](https://github.com/sho-87/kanagawa-paper.nvim/assets/5199715/299eed30-9101-47ca-a8d7-52c5e69d6a57)

**Comment by Yushi5058** [comment]
> @Yushi5058 do you mean consistent colors as in the keywords like `function` being the same color as in the buffer? ive not looked into it too much, but I believe that is quite difficult to do as I think pmenus use the same highlight group for text (but unsure)

Maybe you can see that with the plugin author echasnovski, and there are some merge prs he did for some colorschemes to include his plugin support.

> also, what font are you using? looks nice
I use maple-font, thanks

**Comment by Yushi5058** [comment]
> so for example, this is how it works on my setup (and most setups ive seen):
> 
> - the documentation on the right is syntax highlighted
> - the type is also correctly highlighted (same as buffer)
> - but the name itself is not and is all just the fujiWhite color like regular text
> 
> ![image](https://github.com/sho-87/kanagawa-paper.nvim/assets/5199715/299eed30-9101-47ca-a8d7-52c5e69d6a57)
> 

That's certainly my desired output for the completion plugin I use. It works good on mini.statusline but not on the completion

**Comment by sho-87** [comment]
just installed mini.completion to test it out. doesnt seem like there are docs or item type/kind available in the plugin. are you referring to the bright blue background?
![image](https://github.com/sho-87/kanagawa-paper.nvim/assets/5199715/77da91f2-bafe-4e6c-9bfb-db13758e81e7)

**Comment by sho-87** [comment]
(just pushed an update to change the bright blue)

**Comment by Yushi5058** [comment]
Thank you !
