### ISSUE TITLE
Add mini.nvim from upstream

### ISSUE THREAD

**Issue by KarlEricsson** [sho-87/kanagawa-paper.nvim#6]
Thanks for a great colorscheme! As a heavy user of the mini.nvim plugins I would love to see https://github.com/rebelot/kanagawa.nvim/pull/57 adapted. If you are busy I could try to do it myself and make a PR.

**Comment by sho-87** [comment]
added in 1b719a1d7a62a4985ac7e32132af665389032b0f

I dont use much of the mini ecosystem myself, so let me know if anything looks particularly off

**Comment by KarlEricsson** [comment]
That was fast! 
A few minor suggestions:
Use fujiWhite (or possible dragonWhite) for MiniIconsGrey
Use springViolet1 for MiniStatuslineModeVisual
Use autumntGreen for MiniStatuslineModeInsert and MiniStarterSection

Will let you know if I find something else

**Comment by sho-87** [comment]
for statusline, Im using the same mode colours as lualine just so theres some consistency between the 2. the other changes have been made as well in latest commit
